# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: id.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08id.proto\x12\x07\x65xample\"\x13\n\x02Id\x12\r\n\x05value\x18\x01 \x01(\t\"\x07\n\x05\x45mpty23\n\tIdService\x12&\n\x05GetId\x12\x0e.example.Empty\x1a\x0b.example.Id\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'id_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ID._serialized_start=21
  _ID._serialized_end=40
  _EMPTY._serialized_start=42
  _EMPTY._serialized_end=49
  _IDSERVICE._serialized_start=51
  _IDSERVICE._serialized_end=102
# @@protoc_insertion_point(module_scope)
